version: "3.9"
services:
  front:
    container_name: front
    environment:
      - WATCHPACK_POLLING=true
    build:  
      context: ./front
    ports:
      - "3000:3000"
    volumes:
       - './front/:/code/front'
       - /code/front/app/node_modules
    command: npm start

  back:
    container_name: back
    build:
      context: ./back
    ports:
      - "8000:8000" 
    volumes:
      - ./back/:/code/back

    command: python manage.py runserver 0.0.0.0:8000
  