# Generated by Django 4.1.6 on 2023-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
